default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: protospace_42057_development

test:
  <<: *default
  database: protospace_42057_test

production:
  <<: *default
  database: <%= ENV["PG_DATABASE"] %>
  username: <%= ENV["PG_USER"] %>
  password: <%= ENV["PG_PASSWORD"] %>
  host: <%= ENV["PG_HOST"] %>
